# Aggregate all the ndvi readings ordered from their CSV files
#The files are the ones generated by the "ordenar_lecturas_V0.R" script

############## Functions source
source(file.path("C:","Dropbox","Software","Scripts","r","greenseeker","methods_greenseeker.R", fsep = .Platform$file.sep))

##Get all the CSV files from the corresponding trial,They are separated by folders
#Set the WD
path <- setwd(choose.dir(default = file.path("C:","Dropbox","data","AF", fsep = .Platform$file.sep), caption = "Select folder to work on"))
#Get the name of theworking directory
basenameF <- basename(path)
## Get the names of the files. Expected something like : eg. AF_230_020418_ndvi.csv
ndvisF <- list.files(path = path ,pattern="[0123456789]{6}(_ndvi){1}\\.csv$")
# GET THE DATA
ndvis = lapply(ndvisF, read.table,header = TRUE,sep = ",") #We get a list of dataframes
##Add a column for the date to each dataaframe
for (day in 1:length(ndvisF)) {
  #Traverse the list of dataframes and Get the date from the initial list of files
  ndvis[[day]]$samp_date <- toString(get6DigitDate(ndvisF[day]))
  #We also add a column for the tratment of each plot (AKA ID will disregard the repetition)
  ndvis[[day]]$treatment <- substr(ndvis[[day]]$Plot,2,4) #not include the rep ID in the plot
}
#merge them all in one table, stacking the rows
ndvi_all1 <- Reduce(rbind,ndvis) 
#Average by the treatment
ndvi_by_treatment <- averageNDVI_byTreatment(ndvi_all1)
#ordered by date
ndvi_by_treatment <- ndvi_by_treatment[order(ndvi_by_treatment$samp_date),]
#Make the date format as dd-mm-yy
ndvi_by_treatment$samp_date <- paste(substr(ndvi_by_treatment$samp_date,1,2),substr(ndvi_by_treatment$samp_date,3,4),substr(ndvi_by_treatment$samp_date,5,6),sep="-")
#Save to file, add the prefix of the working directory
write.csv(ndvi_by_treatment,paste0(basenameF,"_ndvi_avg_by_treatment.csv"), row.names=FALSE)
