# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# addFieldb1-b250.py
# Created on: 2014-06-07 12:40:25.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: addFieldb1-b250 <Feature_to_add_250_Fields> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")

# Script arguments
Feature_to_add_250_Fields = arcpy.GetParameterAsText(0)
if Feature_to_add_250_Fields == '#' or not Feature_to_add_250_Fields:
    Feature_to_add_250_Fields = "H140117_BW" # provide a default value if unspecified

# Local variables:
Feature_with_250_fields = Feature_to_add_250_Fields

# Process: For
arcpy.IterateCount_mb("1", "250", "1")

# Process: Add Field
arcpy.AddField_management(Feature_to_add_250_Fields, "B%band_value%", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

