# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# extractOneBandToGDBFeature.py
# Created on: 2016-06-30 11:31:06.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: extractOneBandToGDBFeature <Buffer> <Raster> <Grid> <Folder_to_save_stats> <Stats_table> <Zone_field_and_join_Field> <Create_field_to_save_data> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")
arcpy.ImportToolbox("C:/Dropbox/Software/Scripts/ArcGIS/Herramientas.tbx")

# Set Geoprocessing environments
arcpy.env.snapRaster = "C:\\Dropbox\\data\\AD\\AD_nut\\ndvi_geo\\c160216jlonvi.tif"
arcpy.env.extent = "606004.483 3029183.7528 607206.2229 3030188.6423"

# Script arguments
Buffer = arcpy.GetParameterAsText(0)
if Buffer == '#' or not Buffer:
    Buffer = "C:\\Dropbox\\data\\AD\\AD_nut\\shp\\ad_GS.gdb\\areas\\areas_jlo" # provide a default value if unspecified

Raster = arcpy.GetParameterAsText(1)
if Raster == '#' or not Raster:
    Raster = "C:\\Dropbox\\data\\AD\\AD_nut\\ndvi_geo\\c160216jlonvi.tif" # provide a default value if unspecified

Grid = arcpy.GetParameterAsText(2)
if Grid == '#' or not Grid:
    Grid = "C:\\Dropbox\\data\\AD\\AD_nut\\shp\\ad_GS.gdb\\areas\\areas_jlo" # provide a default value if unspecified

Folder_to_save_stats = arcpy.GetParameterAsText(3)
if Folder_to_save_stats == '#' or not Folder_to_save_stats:
    Folder_to_save_stats = "C:\\Users\\usuario\\Documents\\ArcGIS\\Default.gdb" # provide a default value if unspecified

Stats_table = arcpy.GetParameterAsText(4)
if Stats_table == '#' or not Stats_table:
    Stats_table = "%Folder to save stats%\\%cam_date%_%trial%" # provide a default value if unspecified

Zone_field_and_join_Field = arcpy.GetParameterAsText(5)
if Zone_field_and_join_Field == '#' or not Zone_field_and_join_Field:
    Zone_field_and_join_Field = "Id" # provide a default value if unspecified

Create_field_to_save_data = arcpy.GetParameterAsText(6)
if Create_field_to_save_data == '#' or not Create_field_to_save_data:
    Create_field_to_save_data = "%cam_date%" # provide a default value if unspecified

# Local variables:
areas_jlo_Layer__2_ = Stats_table
acbwypt_bf = areas_jlo_Layer__2_
mean_value = acbwypt_bf
EYTBW__3_ = mean_value
stat_table = Stats_table
raster_name = Raster
date = raster_name
acsamtplotsbf__2_ = date
areas_jlo_Layer = acsamtplotsbf__2_
trial = raster_name
cam = raster_name
cam_date = cam
grid_name = Grid
Expression = "%stat_table%.Mean IS NOT NULL"

# Process: Parse Path (4)
arcpy.ParsePath_mb(Raster, "NAME")

# Process: truncateString
arcpy.gp.toolbox = "C:/Dropbox/Software/Scripts/ArcGIS/Herramientas.tbx";
# Warning: the toolbox C:/Dropbox/Software/Scripts/ArcGIS/Herramientas.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.truncateString(...) with arcpy.truncateString_ALIAS(...)
arcpy.gp.truncateString("1", "7", raster_name)

# Process: truncateString (3)
arcpy.gp.toolbox = "C:/Dropbox/Software/Scripts/ArcGIS/Herramientas.tbx";
# Warning: the toolbox C:/Dropbox/Software/Scripts/ArcGIS/Herramientas.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.truncateString(...) with arcpy.truncateString_ALIAS(...)
arcpy.gp.truncateString("0", "1", raster_name)

# Process: Calculate Value
arcpy.CalculateValue_management("paste(\"%cam%\",\"%date%\")", "def paste(a,y):\\n return str(a)+str(y)", "String")

# Process: Add Field
arcpy.AddField_management(Grid, Create_field_to_save_data, "FLOAT", "8", "3", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(acsamtplotsbf__2_, areas_jlo_Layer, "", "", "OBJECTID OBJECTID VISIBLE NONE;Shape Shape VISIBLE NONE;Id Id VISIBLE NONE;Shape_Length Shape_Length VISIBLE NONE;Shape_Area Shape_Area VISIBLE NONE;area area VISIBLE NONE;%cam_date% %cam_date% VISIBLE NONE")

# Process: truncateString (2)
arcpy.gp.toolbox = "C:/Dropbox/Software/Scripts/ArcGIS/Herramientas.tbx";
# Warning: the toolbox C:/Dropbox/Software/Scripts/ArcGIS/Herramientas.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.truncateString(...) with arcpy.truncateString_ALIAS(...)
arcpy.gp.truncateString("7", "10", raster_name)

# Process: Zonal Statistics as Table
arcpy.gp.ZonalStatisticsAsTable_sa(Buffer, Zone_field_and_join_Field, Raster, Stats_table, "DATA", "MEAN")

# Process: Add Join
arcpy.AddJoin_management(areas_jlo_Layer, Zone_field_and_join_Field, Stats_table, Zone_field_and_join_Field, "KEEP_ALL")

# Process: Parse Path (3)
arcpy.ParsePath_mb(Stats_table, "NAME")

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(areas_jlo_Layer__2_, "NEW_SELECTION", Expression)

# Process: Calculate Field
arcpy.CalculateField_management(acbwypt_bf, "%grid_name%.%Create field to save data%", "round(!%stat_table%.Mean!,3)", "PYTHON", "")

# Process: Remove Join
arcpy.RemoveJoin_management(mean_value, "")

# Process: Parse Path (2)
arcpy.ParsePath_mb(Grid, "NAME")

